var w = window; // Window;
console.warn(w.toString()); // "[object Window]"

w.newProp = "New prop";
console.log(w.newProp); // New prop

/* w: Window
alert: ƒ alert()
applicationCache: ApplicationCache {status: 0, oncached: null, onchecking: null, ondownloading: null, onerror: null, …}
atob: ƒ atob()
btoa: ƒ btoa()
caches: CacheStorage {}
cancelAnimationFrame: ƒ cancelAnimationFrame()
cancelIdleCallback: ƒ cancelIdleCallback()
captureEvents: ƒ captureEvents()
chrome: {loadTimes: ƒ, csi: ƒ}
clearInterval: ƒ clearInterval()
clearTimeout: ƒ clearTimeout()
clientInformation: Navigator {vendorSub: "", productSub: "20030107", vendor: "Google Inc.", maxTouchPoints: 0, hardwareConcurrency: 4, …}
confirm: ƒ confirm()
createImageBitmap: ƒ createImageBitmap()
crypto: Crypto {subtle: SubtleCrypto}
customElements: CustomElementRegistry {}
defaultStatus: ""
defaultstatus: ""
devicePixelRatio: 2
document: document
external: External {}
fetch: ƒ fetch()
find: ƒ find()
frameElement: null
getComputedStyle: ƒ getComputedStyle()
getSelection: ƒ getSelection()
history: History {length: 1, scrollRestoration: "auto", state: null}
indexedDB: IDBFactory {}
innerHeight: 616
innerWidth: 1280
isSecureContext: true
localStorage: Storage {length: 0}
locationbar: BarProp {visible: true}
matchMedia: ƒ matchMedia()
menubar: BarProp {visible: true}
moveBy: ƒ moveBy()
moveTo: ƒ moveTo()
name: ""
navigator: Navigator {vendorSub: "", productSub: "20030107", vendor: "Google Inc.", maxTouchPoints: 0, hardwareConcurrency: 4, …}
onabort: null
onafterprint: null
onanimationend: null
onanimationiteration: null
onanimationstart: null
onappinstalled: null
onauxclick: null
onbeforeinstallprompt: null
onbeforeprint: null
onbeforeunload: null
onblur: null
oncancel: null
oncanplay: null
oncanplaythrough: null
onchange: null
onclick: null
onclose: null
oncontextmenu: null
oncuechange: null
ondblclick: null
ondevicemotion: null
ondeviceorientation: null
ondeviceorientationabsolute: null
ondrag: null
ondragend: null
ondragenter: null
ondragleave: null
ondragover: null
ondragstart: null
ondrop: null
ondurationchange: null
onemptied: null
onended: null
onerror: null
onfocus: null
ongotpointercapture: null
onhashchange: null
oninput: null
oninvalid: null
onkeydown: null
onkeypress: null
onkeyup: null
onlanguagechange: null
onload: null
onloadeddata: null
onloadedmetadata: null
onloadstart: null
onlostpointercapture: null
onmessage: null
onmessageerror: null
onmousedown: null
onmouseenter: null
onmouseleave: null
onmousemove: null
onmouseout: null
onmouseover: null
onmouseup: null
onmousewheel: null
onoffline: null
ononline: null
onpagehide: null
onpageshow: null
onpause: null
onplay: null
onplaying: null
onpointercancel: null
onpointerdown: null
onpointerenter: null
onpointerleave: null
onpointermove: null
onpointerout: null
onpointerover: null
onpointerup: null
onpopstate: null
onprogress: null
onratechange: null
onrejectionhandled: null
onreset: null
onresize: null
onscroll: null
onsearch: null
onseeked: null
onseeking: null
onselect: null
onstalled: null
onstorage: null
onsubmit: null
onsuspend: null
ontimeupdate: null
ontoggle: null
ontransitionend: null
onunhandledrejection: null
onunload: null
onvolumechange: null
onwaiting: null
onwebkitanimationend: null
onwebkitanimationiteration: null
onwebkitanimationstart: null
onwebkittransitionend: null
onwheel: null
open: ƒ open()
openDatabase: ƒ ()
origin: "null"
outerHeight: 726
outerWidth: 1280
pageXOffset: 0
pageYOffset: 0
performance: Performance {timeOrigin: 1542511911332.392, onresourcetimingbufferfull: null, memory: MemoryInfo, navigation: PerformanceNavigation, timing: PerformanceTiming}
personalbar: BarProp {visible: true}
print: ƒ print()
prompt: ƒ prompt()
releaseEvents: ƒ releaseEvents()
requestAnimationFrame: ƒ requestAnimationFrame()
requestIdleCallback: ƒ requestIdleCallback()
resizeBy: ƒ resizeBy()
resizeTo: ƒ resizeTo()
screen: Screen {availWidth: 1280, availHeight: 726, width: 1280, height: 800, colorDepth: 24, …}
screenLeft: 0
screenTop: 23
screenX: 0
screenY: 23
scroll: ƒ scroll()
scrollBy: ƒ scrollBy()
scrollTo: ƒ scrollTo()
scrollX: 0
scrollY: 0
scrollbars: BarProp {visible: true}
sessionStorage: Storage {length: 0}
setInterval: ƒ setInterval()
setTimeout: ƒ setTimeout()
speechSynthesis: SpeechSynthesis {pending: false, speaking: false, paused: false, onvoiceschanged: null}
status: ""
statusbar: BarProp {visible: true}
stop: ƒ stop()
styleMedia: StyleMedia {type: "screen"}
toolbar: BarProp {visible: true}
visualViewport: VisualViewport {offsetLeft: 0, offsetTop: 0, pageLeft: 0, pageTop: 0, width: 1280, …}
w: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
webkitCancelAnimationFrame: ƒ webkitCancelAnimationFrame()
webkitRequestAnimationFrame: ƒ webkitRequestAnimationFrame()
webkitRequestFileSystem: ƒ ()
webkitResolveLocalFileSystemURL: ƒ ()
webkitStorageInfo: DeprecatedStorageInfo {}
window: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
Infinity: Infinity
AbortController: (...)
AbortSignal: (...)
AbsoluteOrientationSensor: (...)
Accelerometer: (...)
AnalyserNode: (...)
AnimationEvent: (...)
ApplicationCache: (...)
ApplicationCacheErrorEvent: (...)
Array: ƒ Array()
ArrayBuffer: ƒ ArrayBuffer()
Atomics: Atomics {load: ƒ, store: ƒ, add: ƒ, sub: ƒ, and: ƒ, …}
Attr: (...)
Audio: (...)
AudioBuffer: (...)
AudioBufferSourceNode: (...)
AudioContext: (...)
AudioDestinationNode: (...)
AudioListener: (...)
AudioNode: (...)
AudioParam: (...)
AudioParamMap: (...)
AudioProcessingEvent: (...)
AudioScheduledSourceNode: (...)
AudioWorklet: (...)
AudioWorkletNode: (...)
AuthenticatorAssertionResponse: (...)
AuthenticatorAttestationResponse: (...)
AuthenticatorResponse: (...)
BarProp: (...)
BaseAudioContext: (...)
BatteryManager: (...)
BeforeInstallPromptEvent: (...)
BeforeUnloadEvent: (...)
BigInt: ƒ BigInt()
BigInt64Array: ƒ BigInt64Array()
BigUint64Array: ƒ BigUint64Array()
BiquadFilterNode: (...)
Blob: (...)
BlobEvent: (...)
Bluetooth: (...)
BluetoothCharacteristicProperties: (...)
BluetoothDevice: (...)
BluetoothRemoteGATTCharacteristic: (...)
BluetoothRemoteGATTDescriptor: (...)
BluetoothRemoteGATTServer: (...)
BluetoothRemoteGATTService: (...)
BluetoothUUID: (...)
Boolean: ƒ Boolean()
BroadcastChannel: (...)
ByteLengthQueuingStrategy: ƒ ByteLengthQueuingStrategy()
CDATASection: (...)
CSS: (...)
CSSConditionRule: (...)
CSSFontFaceRule: (...)
CSSGroupingRule: (...)
CSSImageValue: (...)
CSSImportRule: (...)
CSSKeyframeRule: (...)
CSSKeyframesRule: (...)
CSSKeywordValue: (...)
CSSMathInvert: (...)
CSSMathMax: (...)
CSSMathMin: (...)
CSSMathNegate: (...)
CSSMathProduct: (...)
CSSMathSum: (...)
CSSMathValue: (...)
CSSMatrixComponent: (...)
CSSMediaRule: (...)
CSSNamespaceRule: (...)
CSSNumericArray: (...)
CSSNumericValue: (...)
CSSPageRule: (...)
CSSPerspective: (...)
CSSPositionValue: (...)
CSSRotate: (...)
CSSRule: (...)
CSSRuleList: (...)
CSSScale: (...)
CSSSkew: (...)
CSSSkewX: (...)
CSSSkewY: (...)
CSSStyleDeclaration: (...)
CSSStyleRule: (...)
CSSStyleSheet: (...)
CSSStyleValue: (...)
CSSSupportsRule: (...)
CSSTransformComponent: (...)
CSSTransformValue: (...)
CSSTranslate: (...)
CSSUnitValue: (...)
CSSUnparsedValue: (...)
CSSVariableReferenceValue: (...)
Cache: (...)
CacheStorage: (...)
CanvasCaptureMediaStreamTrack: (...)
CanvasGradient: (...)
CanvasPattern: (...)
CanvasRenderingContext2D: (...)
ChannelMergerNode: (...)
ChannelSplitterNode: (...)
CharacterData: (...)
Clipboard: (...)
ClipboardEvent: (...)
CloseEvent: (...)
Comment: (...)
CompositionEvent: (...)
ConstantSourceNode: (...)
ConvolverNode: (...)
CountQueuingStrategy: ƒ CountQueuingStrategy()
Credential: (...)
CredentialsContainer: (...)
Crypto: (...)
CryptoKey: (...)
CustomElementRegistry: (...)
CustomEvent: (...)
DOMError: (...)
DOMException: (...)
DOMImplementation: (...)
DOMMatrix: (...)
DOMMatrixReadOnly: (...)
DOMParser: (...)
DOMPoint: (...)
DOMPointReadOnly: (...)
DOMQuad: (...)
DOMRect: (...)
DOMRectList: (...)
DOMRectReadOnly: (...)
DOMStringList: (...)
DOMStringMap: (...)
DOMTokenList: (...)
DataTransfer: (...)
DataTransferItem: (...)
DataTransferItemList: (...)
DataView: ƒ DataView()
Date: ƒ Date()
DelayNode: (...)
DeviceMotionEvent: (...)
DeviceOrientationEvent: (...)
Document: (...)
DocumentFragment: (...)
DocumentType: (...)
DragEvent: (...)
DynamicsCompressorNode: (...)
Element: (...)
EnterPictureInPictureEvent: (...)
Error: ƒ Error()
ErrorEvent: (...)
EvalError: ƒ EvalError()
Event: (...)
EventSource: (...)
EventTarget: (...)
FederatedCredential: (...)
File: (...)
FileList: (...)
FileReader: (...)
Float32Array: ƒ Float32Array()
Float64Array: ƒ Float64Array()
FocusEvent: (...)
FontFace: (...)
FontFaceSetLoadEvent: (...)
FormData: (...)
Function: ƒ Function()
GainNode: (...)
Gamepad: (...)
GamepadButton: (...)
GamepadEvent: (...)
GamepadHapticActuator: (...)
Gyroscope: (...)
HTMLAllCollection: (...)
HTMLAnchorElement: (...)
HTMLAreaElement: (...)
HTMLAudioElement: (...)
HTMLBRElement: (...)
HTMLBaseElement: (...)
HTMLBodyElement: (...)
HTMLButtonElement: (...)
HTMLCanvasElement: (...)
HTMLCollection: (...)
HTMLContentElement: (...)
HTMLDListElement: (...)
HTMLDataElement: (...)
HTMLDataListElement: (...)
HTMLDetailsElement: (...)
HTMLDialogElement: (...)
HTMLDirectoryElement: (...)
HTMLDivElement: (...)
HTMLDocument: (...)
HTMLElement: (...)
HTMLEmbedElement: (...)
HTMLFieldSetElement: (...)
HTMLFontElement: (...)
HTMLFormControlsCollection: (...)
HTMLFormElement: (...)
HTMLFrameElement: (...)
HTMLFrameSetElement: (...)
HTMLHRElement: (...)
HTMLHeadElement: (...)
HTMLHeadingElement: (...)
HTMLHtmlElement: (...)
HTMLIFrameElement: (...)
HTMLImageElement: (...)
HTMLInputElement: (...)
HTMLLIElement: (...)
HTMLLabelElement: (...)
HTMLLegendElement: (...)
HTMLLinkElement: (...)
HTMLMapElement: (...)
HTMLMarqueeElement: (...)
HTMLMediaElement: (...)
HTMLMenuElement: (...)
HTMLMetaElement: (...)
HTMLMeterElement: (...)
HTMLModElement: (...)
HTMLOListElement: (...)
HTMLObjectElement: (...)
HTMLOptGroupElement: (...)
HTMLOptionElement: (...)
HTMLOptionsCollection: (...)
HTMLOutputElement: (...)
HTMLParagraphElement: (...)
HTMLParamElement: (...)
HTMLPictureElement: (...)
HTMLPreElement: (...)
HTMLProgressElement: (...)
HTMLQuoteElement: (...)
HTMLScriptElement: (...)
HTMLSelectElement: (...)
HTMLShadowElement: (...)
HTMLSlotElement: (...)
HTMLSourceElement: (...)
HTMLSpanElement: (...)
HTMLStyleElement: (...)
HTMLTableCaptionElement: (...)
HTMLTableCellElement: (...)
HTMLTableColElement: (...)
HTMLTableElement: (...)
HTMLTableRowElement: (...)
HTMLTableSectionElement: (...)
HTMLTemplateElement: (...)
HTMLTextAreaElement: (...)
HTMLTimeElement: (...)
HTMLTitleElement: (...)
HTMLTrackElement: (...)
HTMLUListElement: (...)
HTMLUnknownElement: (...)
HTMLVideoElement: (...)
HashChangeEvent: (...)
Headers: (...)
History: (...)
IDBCursor: (...)
IDBCursorWithValue: (...)
IDBDatabase: (...)
IDBFactory: (...)
IDBIndex: (...)
IDBKeyRange: (...)
IDBObjectStore: (...)
IDBOpenDBRequest: (...)
IDBRequest: (...)
IDBTransaction: (...)
IDBVersionChangeEvent: (...)
IIRFilterNode: (...)
IdleDeadline: (...)
Image: (...)
ImageBitmap: (...)
ImageBitmapRenderingContext: (...)
ImageCapture: (...)
ImageData: (...)
InputDeviceCapabilities: (...)
InputDeviceInfo: (...)
InputEvent: (...)
Int8Array: ƒ Int8Array()
Int16Array: ƒ Int16Array()
Int32Array: ƒ Int32Array()
IntersectionObserver: (...)
IntersectionObserverEntry: (...)
Intl: {DateTimeFormat: ƒ, NumberFormat: ƒ, Collator: ƒ, v8BreakIterator: ƒ, PluralRules: ƒ, …}
JSON: JSON {parse: ƒ, stringify: ƒ, Symbol(Symbol.toStringTag): "JSON"}
Keyboard: (...)
KeyboardEvent: (...)
KeyboardLayoutMap: (...)
LinearAccelerationSensor: (...)
Location: (...)
Lock: (...)
LockManager: (...)
MIDIAccess: (...)
MIDIConnectionEvent: (...)
MIDIInput: (...)
MIDIInputMap: (...)
MIDIMessageEvent: (...)
MIDIOutput: (...)
MIDIOutputMap: (...)
MIDIPort: (...)
Map: ƒ Map()
Math: Math {abs: ƒ, acos: ƒ, acosh: ƒ, asin: ƒ, asinh: ƒ, …}
MediaCapabilities: (...)
MediaCapabilitiesInfo: (...)
MediaDeviceInfo: (...)
MediaDevices: (...)
MediaElementAudioSourceNode: (...)
MediaEncryptedEvent: (...)
MediaError: (...)
MediaKeyMessageEvent: (...)
MediaKeySession: (...)
MediaKeyStatusMap: (...)
MediaKeySystemAccess: (...)
MediaKeys: (...)
MediaList: (...)
MediaQueryList: (...)
MediaQueryListEvent: (...)
MediaRecorder: (...)
MediaSettingsRange: (...)
MediaSource: (...)
MediaStream: (...)
MediaStreamAudioDestinationNode: (...)
MediaStreamAudioSourceNode: (...)
MediaStreamEvent: (...)
MediaStreamTrack: (...)
MediaStreamTrackEvent: (...)
MessageChannel: (...)
MessageEvent: (...)
MessagePort: (...)
MimeType: (...)
MimeTypeArray: (...)
MouseEvent: (...)
MutationEvent: (...)
MutationObserver: (...)
MutationRecord: (...)
NaN: NaN
NamedNodeMap: (...)
NavigationPreloadManager: (...)
Navigator: (...)
NetworkInformation: (...)
Node: (...)
NodeFilter: (...)
NodeIterator: (...)
NodeList: (...)
Notification: (...)
Number: ƒ Number()
Object: ƒ Object()
OfflineAudioCompletionEvent: (...)
OfflineAudioContext: (...)
OffscreenCanvas: (...)
OffscreenCanvasRenderingContext2D: (...)
Option: (...)
OrientationSensor: (...)
OscillatorNode: (...)
OverconstrainedError: (...)
PageTransitionEvent: (...)
PannerNode: (...)
PasswordCredential: (...)
Path2D: (...)
PaymentAddress: (...)
PaymentInstruments: (...)
PaymentManager: (...)
PaymentRequest: (...)
PaymentRequestUpdateEvent: (...)
PaymentResponse: (...)
Performance: (...)
PerformanceEntry: (...)
PerformanceLongTaskTiming: (...)
PerformanceMark: (...)
PerformanceMeasure: (...)
PerformanceNavigation: (...)
PerformanceNavigationTiming: (...)
PerformanceObserver: (...)
PerformanceObserverEntryList: (...)
PerformancePaintTiming: (...)
PerformanceResourceTiming: (...)
PerformanceServerTiming: (...)
PerformanceTiming: (...)
PeriodicWave: (...)
PermissionStatus: (...)
Permissions: (...)
PhotoCapabilities: (...)
PictureInPictureWindow: (...)
Plugin: (...)
PluginArray: (...)
PointerEvent: (...)
PopStateEvent: (...)
Presentation: (...)
PresentationAvailability: (...)
PresentationConnection: (...)
PresentationConnectionAvailableEvent: (...)
PresentationConnectionCloseEvent: (...)
PresentationConnectionList: (...)
PresentationReceiver: (...)
PresentationRequest: (...)
ProcessingInstruction: (...)
ProgressEvent: (...)
Promise: ƒ Promise()
PromiseRejectionEvent: (...)
Proxy: ƒ Proxy()
PublicKeyCredential: (...)
PushManager: (...)
PushSubscription: (...)
PushSubscriptionOptions: (...)
RTCCertificate: (...)
RTCDTMFSender: (...)
RTCDTMFToneChangeEvent: (...)
RTCDataChannel: (...)
RTCDataChannelEvent: (...)
RTCIceCandidate: (...)
RTCPeerConnection: (...)
RTCPeerConnectionIceEvent: (...)
RTCRtpContributingSource: (...)
RTCRtpReceiver: (...)
RTCRtpSender: (...)
RTCRtpTransceiver: (...)
RTCSessionDescription: (...)
RTCStatsReport: (...)
RTCTrackEvent: (...)
RadioNodeList: (...)
Range: (...)
RangeError: ƒ RangeError()
ReadableStream: ƒ ReadableStream()
ReferenceError: ƒ ReferenceError()
Reflect: {defineProperty: ƒ, deleteProperty: ƒ, apply: ƒ, construct: ƒ, get: ƒ, …}
RegExp: ƒ RegExp()
RelativeOrientationSensor: (...)
RemotePlayback: (...)
ReportingObserver: (...)
Request: ƒ Request()
ResizeObserver: (...)
ResizeObserverEntry: (...)
Response: ƒ Response()
SVGAElement: (...)
SVGAngle: (...)
SVGAnimateElement: (...)
SVGAnimateMotionElement: (...)
SVGAnimateTransformElement: (...)
SVGAnimatedAngle: (...)
SVGAnimatedBoolean: (...)
SVGAnimatedEnumeration: (...)
SVGAnimatedInteger: (...)
SVGAnimatedLength: (...)
SVGAnimatedLengthList: (...)
SVGAnimatedNumber: (...)
SVGAnimatedNumberList: (...)
SVGAnimatedPreserveAspectRatio: (...)
SVGAnimatedRect: (...)
SVGAnimatedString: (...)
SVGAnimatedTransformList: (...)
SVGAnimationElement: (...)
SVGCircleElement: (...)
SVGClipPathElement: (...)
SVGComponentTransferFunctionElement: (...)
SVGDefsElement: (...)
SVGDescElement: (...)
SVGDiscardElement: (...)
SVGElement: (...)
SVGEllipseElement: (...)
SVGFEBlendElement: (...)
SVGFEColorMatrixElement: (...)
SVGFEComponentTransferElement: (...)
SVGFECompositeElement: (...)
SVGFEConvolveMatrixElement: (...)
SVGFEDiffuseLightingElement: (...)
SVGFEDisplacementMapElement: (...)
SVGFEDistantLightElement: (...)
SVGFEDropShadowElement: (...)
SVGFEFloodElement: (...)
SVGFEFuncAElement: (...)
SVGFEFuncBElement: (...)
SVGFEFuncGElement: (...)
SVGFEFuncRElement: (...)
SVGFEGaussianBlurElement: (...)
SVGFEImageElement: (...)
SVGFEMergeElement: (...)
SVGFEMergeNodeElement: (...)
SVGFEMorphologyElement: (...)
SVGFEOffsetElement: (...)
SVGFEPointLightElement: (...)
SVGFESpecularLightingElement: (...)
SVGFESpotLightElement: (...)
SVGFETileElement: (...)
SVGFETurbulenceElement: (...)
SVGFilterElement: (...)
SVGForeignObjectElement: (...)
SVGGElement: (...)
SVGGeometryElement: (...)
SVGGradientElement: (...)
SVGGraphicsElement: (...)
SVGImageElement: (...)
SVGLength: (...)
SVGLengthList: (...)
SVGLineElement: (...)
SVGLinearGradientElement: (...)
SVGMPathElement: (...)
SVGMarkerElement: (...)
SVGMaskElement: (...)
SVGMatrix: (...)
SVGMetadataElement: (...)
SVGNumber: (...)
SVGNumberList: (...)
SVGPathElement: (...)
SVGPatternElement: (...)
SVGPoint: (...)
SVGPointList: (...)
SVGPolygonElement: (...)
SVGPolylineElement: (...)
SVGPreserveAspectRatio: (...)
SVGRadialGradientElement: (...)
SVGRect: (...)
SVGRectElement: (...)
SVGSVGElement: (...)
SVGScriptElement: (...)
SVGSetElement: (...)
SVGStopElement: (...)
SVGStringList: (...)
SVGStyleElement: (...)
SVGSwitchElement: (...)
SVGSymbolElement: (...)
SVGTSpanElement: (...)
SVGTextContentElement: (...)
SVGTextElement: (...)
SVGTextPathElement: (...)
SVGTextPositioningElement: (...)
SVGTitleElement: (...)
SVGTransform: (...)
SVGTransformList: (...)
SVGUnitTypes: (...)
SVGUseElement: (...)
SVGViewElement: (...)
Screen: (...)
ScreenOrientation: (...)
ScriptProcessorNode: (...)
SecurityPolicyViolationEvent: (...)
Selection: (...)
Sensor: (...)
SensorErrorEvent: (...)
ServiceWorker: (...)
ServiceWorkerContainer: (...)
ServiceWorkerRegistration: (...)
Set: ƒ Set()
ShadowRoot: (...)
SharedArrayBuffer: ƒ SharedArrayBuffer()
SharedWorker: (...)
SourceBuffer: (...)
SourceBufferList: (...)
SpeechSynthesisEvent: (...)
SpeechSynthesisUtterance: (...)
StaticRange: (...)
StereoPannerNode: (...)
Storage: (...)
StorageEvent: (...)
StorageManager: (...)
String: ƒ String()
StylePropertyMap: (...)
StylePropertyMapReadOnly: (...)
StyleSheet: (...)
StyleSheetList: (...)
SubtleCrypto: (...)
Symbol: ƒ Symbol()
SyncManager: (...)
SyntaxError: ƒ SyntaxError()
TaskAttributionTiming: (...)
Text: (...)
TextDecoder: (...)
TextEncoder: (...)
TextEvent: (...)
TextMetrics: (...)
TextTrack: (...)
TextTrackCue: (...)
TextTrackCueList: (...)
TextTrackList: (...)
TimeRanges: (...)
Touch: (...)
TouchEvent: (...)
TouchList: (...)
TrackEvent: (...)
TransformStream: ƒ TransformStream()
TransitionEvent: (...)
TreeWalker: (...)
TypeError: ƒ TypeError()
UIEvent: (...)
URIError: ƒ URIError()
URL: (...)
URLSearchParams: (...)
USB: (...)
USBAlternateInterface: (...)
USBConfiguration: (...)
USBConnectionEvent: (...)
USBDevice: (...)
USBEndpoint: (...)
USBInTransferResult: (...)
USBInterface: (...)
USBIsochronousInTransferPacket: (...)
USBIsochronousInTransferResult: (...)
USBIsochronousOutTransferPacket: (...)
USBIsochronousOutTransferResult: (...)
USBOutTransferResult: (...)
Uint8Array: ƒ Uint8Array()
Uint8ClampedArray: ƒ Uint8ClampedArray()
Uint16Array: ƒ Uint16Array()
Uint32Array: ƒ Uint32Array()
VTTCue: (...)
ValidityState: (...)
VisualViewport: (...)
WaveShaperNode: (...)
WeakMap: ƒ WeakMap()
WeakSet: ƒ WeakSet()
WebAssembly: WebAssembly {compile: ƒ, validate: ƒ, instantiate: ƒ, compileStreaming: ƒ, instantiateStreaming: ƒ, …}
WebGL2RenderingContext: (...)
WebGLActiveInfo: (...)
WebGLBuffer: (...)
WebGLContextEvent: (...)
WebGLFramebuffer: (...)
WebGLProgram: (...)
WebGLQuery: (...)
WebGLRenderbuffer: (...)
WebGLRenderingContext: (...)
WebGLSampler: (...)
WebGLShader: (...)
WebGLShaderPrecisionFormat: (...)
WebGLSync: (...)
WebGLTexture: (...)
WebGLTransformFeedback: (...)
WebGLUniformLocation: (...)
WebGLVertexArrayObject: (...)
WebKitAnimationEvent: (...)
WebKitCSSMatrix: (...)
WebKitMutationObserver: (...)
WebKitTransitionEvent: (...)
WebSocket: (...)
WheelEvent: (...)
Window: (...)
Worker: (...)
Worklet: (...)
WritableStream: ƒ WritableStream()
XMLDocument: (...)
XMLHttpRequest: (...)
XMLHttpRequestEventTarget: (...)
XMLHttpRequestUpload: (...)
XMLSerializer: (...)
XPathEvaluator: (...)
XPathExpression: (...)
XPathResult: (...)
XSLTProcessor: (...)
blur: (...)
close: (...)
closed: (...)
console: console {debug: ƒ, error: ƒ, info: ƒ, log: ƒ, warn: ƒ, …}
decodeURI: ƒ decodeURI()
decodeURIComponent: ƒ decodeURIComponent()
encodeURI: ƒ encodeURI()
encodeURIComponent: ƒ encodeURIComponent()
escape: ƒ escape()
eval: ƒ eval()
event: undefined
focus: (...)
frames: (...)
isFinite: ƒ isFinite()
isNaN: ƒ isNaN()
length: (...)
location: (...)
offscreenBuffering: true
opener: (...)
parent: (...)
parseFloat: ƒ parseFloat()
parseInt: ƒ parseInt()
postMessage: (...)
self: (...)
top: (...)
undefined: undefined
unescape: ƒ unescape()
webkitMediaStream: (...)
webkitRTCPeerConnection: (...)
webkitSpeechGrammar: (...)
webkitSpeechGrammarList: (...)
webkitSpeechRecognition: (...)
webkitSpeechRecognitionError: (...)
webkitSpeechRecognitionEvent: (...)
webkitURL: (...)
get AbortController: ƒ nativeGetter()
set AbortController: ƒ nativeSetter()
get AbortSignal: ƒ nativeGetter()
set AbortSignal: ƒ nativeSetter()
get AbsoluteOrientationSensor: ƒ nativeGetter()
set AbsoluteOrientationSensor: ƒ nativeSetter()
get Accelerometer: ƒ nativeGetter()
set Accelerometer: ƒ nativeSetter()
get AnalyserNode: ƒ nativeGetter()
set AnalyserNode: ƒ nativeSetter()
get AnimationEvent: ƒ nativeGetter()
set AnimationEvent: ƒ nativeSetter()
get ApplicationCache: ƒ nativeGetter()
set ApplicationCache: ƒ nativeSetter()
get ApplicationCacheErrorEvent: ƒ nativeGetter()
set ApplicationCacheErrorEvent: ƒ nativeSetter()
get Attr: ƒ nativeGetter()
set Attr: ƒ nativeSetter()
get Audio: ƒ nativeGetter()
set Audio: ƒ nativeSetter()
get AudioBuffer: ƒ nativeGetter()
set AudioBuffer: ƒ nativeSetter()
get AudioBufferSourceNode: ƒ nativeGetter()
set AudioBufferSourceNode: ƒ nativeSetter()
get AudioContext: ƒ nativeGetter()
set AudioContext: ƒ nativeSetter()
get AudioDestinationNode: ƒ nativeGetter()
set AudioDestinationNode: ƒ nativeSetter()
get AudioListener: ƒ nativeGetter()
set AudioListener: ƒ nativeSetter()
get AudioNode: ƒ nativeGetter()
set AudioNode: ƒ nativeSetter()
get AudioParam: ƒ nativeGetter()
set AudioParam: ƒ nativeSetter()
get AudioParamMap: ƒ nativeGetter()
set AudioParamMap: ƒ nativeSetter()
get AudioProcessingEvent: ƒ nativeGetter()
set AudioProcessingEvent: ƒ nativeSetter()
get AudioScheduledSourceNode: ƒ nativeGetter()
set AudioScheduledSourceNode: ƒ nativeSetter()
get AudioWorklet: ƒ nativeGetter()
set AudioWorklet: ƒ nativeSetter()
get AudioWorkletNode: ƒ nativeGetter()
set AudioWorkletNode: ƒ nativeSetter()
get AuthenticatorAssertionResponse: ƒ nativeGetter()
set AuthenticatorAssertionResponse: ƒ nativeSetter()
get AuthenticatorAttestationResponse: ƒ nativeGetter()
set AuthenticatorAttestationResponse: ƒ nativeSetter()
get AuthenticatorResponse: ƒ nativeGetter()
set AuthenticatorResponse: ƒ nativeSetter()
get BarProp: ƒ nativeGetter()
set BarProp: ƒ nativeSetter()
get BaseAudioContext: ƒ nativeGetter()
set BaseAudioContext: ƒ nativeSetter()
get BatteryManager: ƒ nativeGetter()
set BatteryManager: ƒ nativeSetter()
get BeforeInstallPromptEvent: ƒ nativeGetter()
set BeforeInstallPromptEvent: ƒ nativeSetter()
get BeforeUnloadEvent: ƒ nativeGetter()
set BeforeUnloadEvent: ƒ nativeSetter()
get BiquadFilterNode: ƒ nativeGetter()
set BiquadFilterNode: ƒ nativeSetter()
get Blob: ƒ nativeGetter()
set Blob: ƒ nativeSetter()
get BlobEvent: ƒ nativeGetter()
set BlobEvent: ƒ nativeSetter()
get Bluetooth: ƒ nativeGetter()
set Bluetooth: ƒ nativeSetter()
get BluetoothCharacteristicProperties: ƒ nativeGetter()
set BluetoothCharacteristicProperties: ƒ nativeSetter()
get BluetoothDevice: ƒ nativeGetter()
set BluetoothDevice: ƒ nativeSetter()
get BluetoothRemoteGATTCharacteristic: ƒ nativeGetter()
set BluetoothRemoteGATTCharacteristic: ƒ nativeSetter()
get BluetoothRemoteGATTDescriptor: ƒ nativeGetter()
set BluetoothRemoteGATTDescriptor: ƒ nativeSetter()
get BluetoothRemoteGATTServer: ƒ nativeGetter()
set BluetoothRemoteGATTServer: ƒ nativeSetter()
get BluetoothRemoteGATTService: ƒ nativeGetter()
set BluetoothRemoteGATTService: ƒ nativeSetter()
get BluetoothUUID: ƒ nativeGetter()
set BluetoothUUID: ƒ nativeSetter()
get BroadcastChannel: ƒ nativeGetter()
set BroadcastChannel: ƒ nativeSetter()
get CDATASection: ƒ nativeGetter()
set CDATASection: ƒ nativeSetter()
get CSS: ƒ nativeGetter()
set CSS: ƒ nativeSetter()
get CSSConditionRule: ƒ nativeGetter()
set CSSConditionRule: ƒ nativeSetter()
get CSSFontFaceRule: ƒ nativeGetter()
set CSSFontFaceRule: ƒ nativeSetter()
get CSSGroupingRule: ƒ nativeGetter()
set CSSGroupingRule: ƒ nativeSetter()
get CSSImageValue: ƒ nativeGetter()
set CSSImageValue: ƒ nativeSetter()
get CSSImportRule: ƒ nativeGetter()
set CSSImportRule: ƒ nativeSetter()
get CSSKeyframeRule: ƒ nativeGetter()
set CSSKeyframeRule: ƒ nativeSetter()
get CSSKeyframesRule: ƒ nativeGetter()
set CSSKeyframesRule: ƒ nativeSetter()
get CSSKeywordValue: ƒ nativeGetter()
set CSSKeywordValue: ƒ nativeSetter()
get CSSMathInvert: ƒ nativeGetter()
set CSSMathInvert: ƒ nativeSetter()
get CSSMathMax: ƒ nativeGetter()
set CSSMathMax: ƒ nativeSetter()
get CSSMathMin: ƒ nativeGetter()
set CSSMathMin: ƒ nativeSetter()
get CSSMathNegate: ƒ nativeGetter()
set CSSMathNegate: ƒ nativeSetter()
get CSSMathProduct: ƒ nativeGetter()
set CSSMathProduct: ƒ nativeSetter()
get CSSMathSum: ƒ nativeGetter()
set CSSMathSum: ƒ nativeSetter()
get CSSMathValue: ƒ nativeGetter()
set CSSMathValue: ƒ nativeSetter()
get CSSMatrixComponent: ƒ nativeGetter()
set CSSMatrixComponent: ƒ nativeSetter()
get CSSMediaRule: ƒ nativeGetter()
set CSSMediaRule: ƒ nativeSetter()
get CSSNamespaceRule: ƒ nativeGetter()
set CSSNamespaceRule: ƒ nativeSetter()
get CSSNumericArray: ƒ nativeGetter()
set CSSNumericArray: ƒ nativeSetter()
get CSSNumericValue: ƒ nativeGetter()
set CSSNumericValue: ƒ nativeSetter()
get CSSPageRule: ƒ nativeGetter()
set CSSPageRule: ƒ nativeSetter()
get CSSPerspective: ƒ nativeGetter()
set CSSPerspective: ƒ nativeSetter()
get CSSPositionValue: ƒ nativeGetter()
set CSSPositionValue: ƒ nativeSetter()
get CSSRotate: ƒ nativeGetter()
set CSSRotate: ƒ nativeSetter()
get CSSRule: ƒ nativeGetter()
set CSSRule: ƒ nativeSetter()
get CSSRuleList: ƒ nativeGetter()
set CSSRuleList: ƒ nativeSetter()
get CSSScale: ƒ nativeGetter()
set CSSScale: ƒ nativeSetter()
get CSSSkew: ƒ nativeGetter()
set CSSSkew: ƒ nativeSetter()
get CSSSkewX: ƒ nativeGetter()
set CSSSkewX: ƒ nativeSetter()
get CSSSkewY: ƒ nativeGetter()
set CSSSkewY: ƒ nativeSetter()
get CSSStyleDeclaration: ƒ nativeGetter()
set CSSStyleDeclaration: ƒ nativeSetter()
get CSSStyleRule: ƒ nativeGetter()
set CSSStyleRule: ƒ nativeSetter()
get CSSStyleSheet: ƒ nativeGetter()
set CSSStyleSheet: ƒ nativeSetter()
get CSSStyleValue: ƒ nativeGetter()
set CSSStyleValue: ƒ nativeSetter()
get CSSSupportsRule: ƒ nativeGetter()
set CSSSupportsRule: ƒ nativeSetter()
get CSSTransformComponent: ƒ nativeGetter()
set CSSTransformComponent: ƒ nativeSetter()
get CSSTransformValue: ƒ nativeGetter()
set CSSTransformValue: ƒ nativeSetter()
get CSSTranslate: ƒ nativeGetter()
set CSSTranslate: ƒ nativeSetter()
get CSSUnitValue: ƒ nativeGetter()
set CSSUnitValue: ƒ nativeSetter()
get CSSUnparsedValue: ƒ nativeGetter()
set CSSUnparsedValue: ƒ nativeSetter()
get CSSVariableReferenceValue: ƒ nativeGetter()
set CSSVariableReferenceValue: ƒ nativeSetter()
get Cache: ƒ nativeGetter()
set Cache: ƒ nativeSetter()
get CacheStorage: ƒ nativeGetter()
set CacheStorage: ƒ nativeSetter()
get CanvasCaptureMediaStreamTrack: ƒ nativeGetter()
set CanvasCaptureMediaStreamTrack: ƒ nativeSetter()
get CanvasGradient: ƒ nativeGetter()
set CanvasGradient: ƒ nativeSetter()
get CanvasPattern: ƒ nativeGetter()
set CanvasPattern: ƒ nativeSetter()
get CanvasRenderingContext2D: ƒ nativeGetter()
set CanvasRenderingContext2D: ƒ nativeSetter()
get ChannelMergerNode: ƒ nativeGetter()
set ChannelMergerNode: ƒ nativeSetter()
get ChannelSplitterNode: ƒ nativeGetter()
set ChannelSplitterNode: ƒ nativeSetter()
get CharacterData: ƒ nativeGetter()
set CharacterData: ƒ nativeSetter()
get Clipboard: ƒ nativeGetter()
set Clipboard: ƒ nativeSetter()
get ClipboardEvent: ƒ nativeGetter()
set ClipboardEvent: ƒ nativeSetter()
get CloseEvent: ƒ nativeGetter()
set CloseEvent: ƒ nativeSetter()
get Comment: ƒ nativeGetter()
set Comment: ƒ nativeSetter()
get CompositionEvent: ƒ nativeGetter()
set CompositionEvent: ƒ nativeSetter()
get ConstantSourceNode: ƒ nativeGetter()
set ConstantSourceNode: ƒ nativeSetter()
get ConvolverNode: ƒ nativeGetter()
set ConvolverNode: ƒ nativeSetter()
get Credential: ƒ nativeGetter()
set Credential: ƒ nativeSetter()
get CredentialsContainer: ƒ nativeGetter()
set CredentialsContainer: ƒ nativeSetter()
get Crypto: ƒ nativeGetter()
set Crypto: ƒ nativeSetter()
get CryptoKey: ƒ nativeGetter()
set CryptoKey: ƒ nativeSetter()
get CustomElementRegistry: ƒ nativeGetter()
set CustomElementRegistry: ƒ nativeSetter()
get CustomEvent: ƒ nativeGetter()
set CustomEvent: ƒ nativeSetter()
get DOMError: ƒ nativeGetter()
set DOMError: ƒ nativeSetter()
get DOMException: ƒ nativeGetter()
set DOMException: ƒ nativeSetter()
get DOMImplementation: ƒ nativeGetter()
set DOMImplementation: ƒ nativeSetter()
get DOMMatrix: ƒ nativeGetter()
set DOMMatrix: ƒ nativeSetter()
get DOMMatrixReadOnly: ƒ nativeGetter()
set DOMMatrixReadOnly: ƒ nativeSetter()
get DOMParser: ƒ nativeGetter()
set DOMParser: ƒ nativeSetter()
get DOMPoint: ƒ nativeGetter()
set DOMPoint: ƒ nativeSetter()
get DOMPointReadOnly: ƒ nativeGetter()
set DOMPointReadOnly: ƒ nativeSetter()
get DOMQuad: ƒ nativeGetter()
set DOMQuad: ƒ nativeSetter()
get DOMRect: ƒ nativeGetter()
set DOMRect: ƒ nativeSetter()
get DOMRectList: ƒ nativeGetter()
set DOMRectList: ƒ nativeSetter()
get DOMRectReadOnly: ƒ nativeGetter()
set DOMRectReadOnly: ƒ nativeSetter()
get DOMStringList: ƒ nativeGetter()
set DOMStringList: ƒ nativeSetter()
get DOMStringMap: ƒ nativeGetter()
set DOMStringMap: ƒ nativeSetter()
get DOMTokenList: ƒ nativeGetter()
set DOMTokenList: ƒ nativeSetter()
get DataTransfer: ƒ nativeGetter()
set DataTransfer: ƒ nativeSetter()
get DataTransferItem: ƒ nativeGetter()
set DataTransferItem: ƒ nativeSetter()
get DataTransferItemList: ƒ nativeGetter()
set DataTransferItemList: ƒ nativeSetter()
get DelayNode: ƒ nativeGetter()
set DelayNode: ƒ nativeSetter()
get DeviceMotionEvent: ƒ nativeGetter()
set DeviceMotionEvent: ƒ nativeSetter()
get DeviceOrientationEvent: ƒ nativeGetter()
set DeviceOrientationEvent: ƒ nativeSetter()
get Document: ƒ nativeGetter()
set Document: ƒ nativeSetter()
get DocumentFragment: ƒ nativeGetter()
set DocumentFragment: ƒ nativeSetter()
get DocumentType: ƒ nativeGetter()
set DocumentType: ƒ nativeSetter()
get DragEvent: ƒ nativeGetter()
set DragEvent: ƒ nativeSetter()
get DynamicsCompressorNode: ƒ nativeGetter()
set DynamicsCompressorNode: ƒ nativeSetter()
get Element: ƒ nativeGetter()
set Element: ƒ nativeSetter()
get EnterPictureInPictureEvent: ƒ nativeGetter()
set EnterPictureInPictureEvent: ƒ nativeSetter()
get ErrorEvent: ƒ nativeGetter()
set ErrorEvent: ƒ nativeSetter()
get Event: ƒ nativeGetter()
set Event: ƒ nativeSetter()
get EventSource: ƒ nativeGetter()
set EventSource: ƒ nativeSetter()
get EventTarget: ƒ nativeGetter()
set EventTarget: ƒ nativeSetter()
get FederatedCredential: ƒ nativeGetter()
set FederatedCredential: ƒ nativeSetter()
get File: ƒ nativeGetter()
set File: ƒ nativeSetter()
get FileList: ƒ nativeGetter()
set FileList: ƒ nativeSetter()
get FileReader: ƒ nativeGetter()
set FileReader: ƒ nativeSetter()
get FocusEvent: ƒ nativeGetter()
set FocusEvent: ƒ nativeSetter()
get FontFace: ƒ nativeGetter()
set FontFace: ƒ nativeSetter()
get FontFaceSetLoadEvent: ƒ nativeGetter()
set FontFaceSetLoadEvent: ƒ nativeSetter()
get FormData: ƒ nativeGetter()
set FormData: ƒ nativeSetter()
get GainNode: ƒ nativeGetter()
set GainNode: ƒ nativeSetter()
get Gamepad: ƒ nativeGetter()
set Gamepad: ƒ nativeSetter()
get GamepadButton: ƒ nativeGetter()
set GamepadButton: ƒ nativeSetter()
get GamepadEvent: ƒ nativeGetter()
set GamepadEvent: ƒ nativeSetter()
get GamepadHapticActuator: ƒ nativeGetter()
set GamepadHapticActuator: ƒ nativeSetter()
get Gyroscope: ƒ nativeGetter()
set Gyroscope: ƒ nativeSetter()
get HTMLAllCollection: ƒ nativeGetter()
set HTMLAllCollection: ƒ nativeSetter()
get HTMLAnchorElement: ƒ nativeGetter()
set HTMLAnchorElement: ƒ nativeSetter()
get HTMLAreaElement: ƒ nativeGetter()
set HTMLAreaElement: ƒ nativeSetter()
get HTMLAudioElement: ƒ nativeGetter()
set HTMLAudioElement: ƒ nativeSetter()
get HTMLBRElement: ƒ nativeGetter()
set HTMLBRElement: ƒ nativeSetter()
get HTMLBaseElement: ƒ nativeGetter()
set HTMLBaseElement: ƒ nativeSetter()
get HTMLBodyElement: ƒ nativeGetter()
set HTMLBodyElement: ƒ nativeSetter()
get HTMLButtonElement: ƒ nativeGetter()
set HTMLButtonElement: ƒ nativeSetter()
get HTMLCanvasElement: ƒ nativeGetter()
set HTMLCanvasElement: ƒ nativeSetter()
get HTMLCollection: ƒ nativeGetter()
set HTMLCollection: ƒ nativeSetter()
get HTMLContentElement: ƒ nativeGetter()
set HTMLContentElement: ƒ nativeSetter()
get HTMLDListElement: ƒ nativeGetter()
set HTMLDListElement: ƒ nativeSetter()
get HTMLDataElement: ƒ nativeGetter()
set HTMLDataElement: ƒ nativeSetter()
get HTMLDataListElement: ƒ nativeGetter()
set HTMLDataListElement: ƒ nativeSetter()
get HTMLDetailsElement: ƒ nativeGetter()
set HTMLDetailsElement: ƒ nativeSetter()
get HTMLDialogElement: ƒ nativeGetter()
set HTMLDialogElement: ƒ nativeSetter()
get HTMLDirectoryElement: ƒ nativeGetter()
set HTMLDirectoryElement: ƒ nativeSetter()
get HTMLDivElement: ƒ nativeGetter()
set HTMLDivElement: ƒ nativeSetter()
get HTMLDocument: ƒ nativeGetter()
set HTMLDocument: ƒ nativeSetter()
get HTMLElement: ƒ nativeGetter()
set HTMLElement: ƒ nativeSetter()
get HTMLEmbedElement: ƒ nativeGetter()
set HTMLEmbedElement: ƒ nativeSetter()
get HTMLFieldSetElement: ƒ nativeGetter()
set HTMLFieldSetElement: ƒ nativeSetter()
get HTMLFontElement: ƒ nativeGetter()
set HTMLFontElement: ƒ nativeSetter()
get HTMLFormControlsCollection: ƒ nativeGetter()
set HTMLFormControlsCollection: ƒ nativeSetter()
get HTMLFormElement: ƒ nativeGetter()
set HTMLFormElement: ƒ nativeSetter()
get HTMLFrameElement: ƒ nativeGetter()
set HTMLFrameElement: ƒ nativeSetter()
get HTMLFrameSetElement: ƒ nativeGetter()
set HTMLFrameSetElement: ƒ nativeSetter()
get HTMLHRElement: ƒ nativeGetter()
set HTMLHRElement: ƒ nativeSetter()
get HTMLHeadElement: ƒ nativeGetter()
set HTMLHeadElement: ƒ nativeSetter()
get HTMLHeadingElement: ƒ nativeGetter()
set HTMLHeadingElement: ƒ nativeSetter()
get HTMLHtmlElement: ƒ nativeGetter()
set HTMLHtmlElement: ƒ nativeSetter()
get HTMLIFrameElement: ƒ nativeGetter()
set HTMLIFrameElement: ƒ nativeSetter()
get HTMLImageElement: ƒ nativeGetter()
set HTMLImageElement: ƒ nativeSetter()
get HTMLInputElement: ƒ nativeGetter()
set HTMLInputElement: ƒ nativeSetter()
get HTMLLIElement: ƒ nativeGetter()
set HTMLLIElement: ƒ nativeSetter()
get HTMLLabelElement: ƒ nativeGetter()
set HTMLLabelElement: ƒ nativeSetter()
get HTMLLegendElement: ƒ nativeGetter()
set HTMLLegendElement: ƒ nativeSetter()
get HTMLLinkElement: ƒ nativeGetter()
set HTMLLinkElement: ƒ nativeSetter()
get HTMLMapElement: ƒ nativeGetter()
set HTMLMapElement: ƒ nativeSetter()
get HTMLMarqueeElement: ƒ nativeGetter()
set HTMLMarqueeElement: ƒ nativeSetter()
get HTMLMediaElement: ƒ nativeGetter()
set HTMLMediaElement: ƒ nativeSetter()
get HTMLMenuElement: ƒ nativeGetter()
set HTMLMenuElement: ƒ nativeSetter()
get HTMLMetaElement: ƒ nativeGetter()
set HTMLMetaElement: ƒ nativeSetter()
get HTMLMeterElement: ƒ nativeGetter()
set HTMLMeterElement: ƒ nativeSetter()
get HTMLModElement: ƒ nativeGetter()
set HTMLModElement: ƒ nativeSetter()
get HTMLOListElement: ƒ nativeGetter()
set HTMLOListElement: ƒ nativeSetter()
get HTMLObjectElement: ƒ nativeGetter()
set HTMLObjectElement: ƒ nativeSetter()
get HTMLOptGroupElement: ƒ nativeGetter()
set HTMLOptGroupElement: ƒ nativeSetter()
get HTMLOptionElement: ƒ nativeGetter()
set HTMLOptionElement: ƒ nativeSetter()
get HTMLOptionsCollection: ƒ nativeGetter()
set HTMLOptionsCollection: ƒ nativeSetter()
get HTMLOutputElement: ƒ nativeGetter()
set HTMLOutputElement: ƒ nativeSetter()
get HTMLParagraphElement: ƒ nativeGetter()
set HTMLParagraphElement: ƒ nativeSetter()
get HTMLParamElement: ƒ nativeGetter()
set HTMLParamElement: ƒ nativeSetter()
get HTMLPictureElement: ƒ nativeGetter()
set HTMLPictureElement: ƒ nativeSetter()
get HTMLPreElement: ƒ nativeGetter()
set HTMLPreElement: ƒ nativeSetter()
get HTMLProgressElement: ƒ nativeGetter()
set HTMLProgressElement: ƒ nativeSetter()
get HTMLQuoteElement: ƒ nativeGetter()
set HTMLQuoteElement: ƒ nativeSetter()
get HTMLScriptElement: ƒ nativeGetter()
set HTMLScriptElement: ƒ nativeSetter()
get HTMLSelectElement: ƒ nativeGetter()
set HTMLSelectElement: ƒ nativeSetter()
get HTMLShadowElement: ƒ nativeGetter()
set HTMLShadowElement: ƒ nativeSetter()
get HTMLSlotElement: ƒ nativeGetter()
set HTMLSlotElement: ƒ nativeSetter()
get HTMLSourceElement: ƒ nativeGetter()
set HTMLSourceElement: ƒ nativeSetter()
get HTMLSpanElement: ƒ nativeGetter()
set HTMLSpanElement: ƒ nativeSetter()
get HTMLStyleElement: ƒ nativeGetter()
set HTMLStyleElement: ƒ nativeSetter()
get HTMLTableCaptionElement: ƒ nativeGetter()
set HTMLTableCaptionElement: ƒ nativeSetter()
get HTMLTableCellElement: ƒ nativeGetter()
set HTMLTableCellElement: ƒ nativeSetter()
get HTMLTableColElement: ƒ nativeGetter()
set HTMLTableColElement: ƒ nativeSetter()
get HTMLTableElement: ƒ nativeGetter()
set HTMLTableElement: ƒ nativeSetter()
get HTMLTableRowElement: ƒ nativeGetter()
set HTMLTableRowElement: ƒ nativeSetter()
get HTMLTableSectionElement: ƒ nativeGetter()
set HTMLTableSectionElement: ƒ nativeSetter()
get HTMLTemplateElement: ƒ nativeGetter()
set HTMLTemplateElement: ƒ nativeSetter()
get HTMLTextAreaElement: ƒ nativeGetter()
set HTMLTextAreaElement: ƒ nativeSetter()
get HTMLTimeElement: ƒ nativeGetter()
set HTMLTimeElement: ƒ nativeSetter()
get HTMLTitleElement: ƒ nativeGetter()
set HTMLTitleElement: ƒ nativeSetter()
get HTMLTrackElement: ƒ nativeGetter()
set HTMLTrackElement: ƒ nativeSetter()
get HTMLUListElement: ƒ nativeGetter()
set HTMLUListElement: ƒ nativeSetter()
get HTMLUnknownElement: ƒ nativeGetter()
set HTMLUnknownElement: ƒ nativeSetter()
get HTMLVideoElement: ƒ nativeGetter()
set HTMLVideoElement: ƒ nativeSetter()
get HashChangeEvent: ƒ nativeGetter()
set HashChangeEvent: ƒ nativeSetter()
get Headers: ƒ nativeGetter()
set Headers: ƒ nativeSetter()
get History: ƒ nativeGetter()
set History: ƒ nativeSetter()
get IDBCursor: ƒ nativeGetter()
set IDBCursor: ƒ nativeSetter()
get IDBCursorWithValue: ƒ nativeGetter()
set IDBCursorWithValue: ƒ nativeSetter()
get IDBDatabase: ƒ nativeGetter()
set IDBDatabase: ƒ nativeSetter()
get IDBFactory: ƒ nativeGetter()
set IDBFactory: ƒ nativeSetter()
get IDBIndex: ƒ nativeGetter()
set IDBIndex: ƒ nativeSetter()
get IDBKeyRange: ƒ nativeGetter()
set IDBKeyRange: ƒ nativeSetter()
get IDBObjectStore: ƒ nativeGetter()
set IDBObjectStore: ƒ nativeSetter()
get IDBOpenDBRequest: ƒ nativeGetter()
set IDBOpenDBRequest: ƒ nativeSetter()
get IDBRequest: ƒ nativeGetter()
set IDBRequest: ƒ nativeSetter()
get IDBTransaction: ƒ nativeGetter()
set IDBTransaction: ƒ nativeSetter()
get IDBVersionChangeEvent: ƒ nativeGetter()
set IDBVersionChangeEvent: ƒ nativeSetter()
get IIRFilterNode: ƒ nativeGetter()
set IIRFilterNode: ƒ nativeSetter()
get IdleDeadline: ƒ nativeGetter()
set IdleDeadline: ƒ nativeSetter()
get Image: ƒ nativeGetter()
set Image: ƒ nativeSetter()
get ImageBitmap: ƒ nativeGetter()
set ImageBitmap: ƒ nativeSetter()
get ImageBitmapRenderingContext: ƒ nativeGetter()
set ImageBitmapRenderingContext: ƒ nativeSetter()
get ImageCapture: ƒ nativeGetter()
set ImageCapture: ƒ nativeSetter()
get ImageData: ƒ nativeGetter()
set ImageData: ƒ nativeSetter()
get InputDeviceCapabilities: ƒ nativeGetter()
set InputDeviceCapabilities: ƒ nativeSetter()
get InputDeviceInfo: ƒ nativeGetter()
set InputDeviceInfo: ƒ nativeSetter()
get InputEvent: ƒ nativeGetter()
set InputEvent: ƒ nativeSetter()
get IntersectionObserver: ƒ nativeGetter()
set IntersectionObserver: ƒ nativeSetter()
get IntersectionObserverEntry: ƒ nativeGetter()
set IntersectionObserverEntry: ƒ nativeSetter()
get Keyboard: ƒ nativeGetter()
set Keyboard: ƒ nativeSetter()
get KeyboardEvent: ƒ nativeGetter()
set KeyboardEvent: ƒ nativeSetter()
get KeyboardLayoutMap: ƒ nativeGetter()
set KeyboardLayoutMap: ƒ nativeSetter()
get LinearAccelerationSensor: ƒ nativeGetter()
set LinearAccelerationSensor: ƒ nativeSetter()
get Location: ƒ nativeGetter()
set Location: ƒ nativeSetter()
get Lock: ƒ nativeGetter()
set Lock: ƒ nativeSetter()
get LockManager: ƒ nativeGetter()
set LockManager: ƒ nativeSetter()
get MIDIAccess: ƒ nativeGetter()
set MIDIAccess: ƒ nativeSetter()
get MIDIConnectionEvent: ƒ nativeGetter()
set MIDIConnectionEvent: ƒ nativeSetter()
get MIDIInput: ƒ nativeGetter()
set MIDIInput: ƒ nativeSetter()
get MIDIInputMap: ƒ nativeGetter()
set MIDIInputMap: ƒ nativeSetter()
get MIDIMessageEvent: ƒ nativeGetter()
set MIDIMessageEvent: ƒ nativeSetter()
get MIDIOutput: ƒ nativeGetter()
set MIDIOutput: ƒ nativeSetter()
get MIDIOutputMap: ƒ nativeGetter()
set MIDIOutputMap: ƒ nativeSetter()
get MIDIPort: ƒ nativeGetter()
set MIDIPort: ƒ nativeSetter()
get MediaCapabilities: ƒ nativeGetter()
set MediaCapabilities: ƒ nativeSetter()
get MediaCapabilitiesInfo: ƒ nativeGetter()
set MediaCapabilitiesInfo: ƒ nativeSetter()
get MediaDeviceInfo: ƒ nativeGetter()
set MediaDeviceInfo: ƒ nativeSetter()
get MediaDevices: ƒ nativeGetter()
set MediaDevices: ƒ nativeSetter()
get MediaElementAudioSourceNode: ƒ nativeGetter()
set MediaElementAudioSourceNode: ƒ nativeSetter()
get MediaEncryptedEvent: ƒ nativeGetter()
set MediaEncryptedEvent: ƒ nativeSetter()
get MediaError: ƒ nativeGetter()
set MediaError: ƒ nativeSetter()
get MediaKeyMessageEvent: ƒ nativeGetter()
set MediaKeyMessageEvent: ƒ nativeSetter()
get MediaKeySession: ƒ nativeGetter()
set MediaKeySession: ƒ nativeSetter()
get MediaKeyStatusMap: ƒ nativeGetter()
set MediaKeyStatusMap: ƒ nativeSetter()
get MediaKeySystemAccess: ƒ nativeGetter()
set MediaKeySystemAccess: ƒ nativeSetter()
get MediaKeys: ƒ nativeGetter()
set MediaKeys: ƒ nativeSetter()
get MediaList: ƒ nativeGetter()
set MediaList: ƒ nativeSetter()
get MediaQueryList: ƒ nativeGetter()
set MediaQueryList: ƒ nativeSetter()
get MediaQueryListEvent: ƒ nativeGetter()
set MediaQueryListEvent: ƒ nativeSetter()
get MediaRecorder: ƒ nativeGetter()
set MediaRecorder: ƒ nativeSetter()
get MediaSettingsRange: ƒ nativeGetter()
set MediaSettingsRange: ƒ nativeSetter()
get MediaSource: ƒ nativeGetter()
set MediaSource: ƒ nativeSetter()
get MediaStream: ƒ nativeGetter()
set MediaStream: ƒ nativeSetter()
get MediaStreamAudioDestinationNode: ƒ nativeGetter()
set MediaStreamAudioDestinationNode: ƒ nativeSetter()
get MediaStreamAudioSourceNode: ƒ nativeGetter()
set MediaStreamAudioSourceNode: ƒ nativeSetter()
get MediaStreamEvent: ƒ nativeGetter()
set MediaStreamEvent: ƒ nativeSetter()
get MediaStreamTrack: ƒ nativeGetter()
set MediaStreamTrack: ƒ nativeSetter()
get MediaStreamTrackEvent: ƒ nativeGetter()
set MediaStreamTrackEvent: ƒ nativeSetter()
get MessageChannel: ƒ nativeGetter()
set MessageChannel: ƒ nativeSetter()
get MessageEvent: ƒ nativeGetter()
set MessageEvent: ƒ nativeSetter()
get MessagePort: ƒ nativeGetter()
set MessagePort: ƒ nativeSetter()
get MimeType: ƒ nativeGetter()
set MimeType: ƒ nativeSetter()
get MimeTypeArray: ƒ nativeGetter()
set MimeTypeArray: ƒ nativeSetter()
get MouseEvent: ƒ nativeGetter()
set MouseEvent: ƒ nativeSetter()
get MutationEvent: ƒ nativeGetter()
set MutationEvent: ƒ nativeSetter()
get MutationObserver: ƒ nativeGetter()
set MutationObserver: ƒ nativeSetter()
get MutationRecord: ƒ nativeGetter()
set MutationRecord: ƒ nativeSetter()
get NamedNodeMap: ƒ nativeGetter()
set NamedNodeMap: ƒ nativeSetter()
get NavigationPreloadManager: ƒ nativeGetter()
set NavigationPreloadManager: ƒ nativeSetter()
get Navigator: ƒ nativeGetter()
set Navigator: ƒ nativeSetter()
get NetworkInformation: ƒ nativeGetter()
set NetworkInformation: ƒ nativeSetter()
get Node: ƒ nativeGetter()
set Node: ƒ nativeSetter()
get NodeFilter: ƒ nativeGetter()
set NodeFilter: ƒ nativeSetter()
get NodeIterator: ƒ nativeGetter()
set NodeIterator: ƒ nativeSetter()
get NodeList: ƒ nativeGetter()
set NodeList: ƒ nativeSetter()
get Notification: ƒ nativeGetter()
set Notification: ƒ nativeSetter()
get OfflineAudioCompletionEvent: ƒ nativeGetter()
set OfflineAudioCompletionEvent: ƒ nativeSetter()
get OfflineAudioContext: ƒ nativeGetter()
set OfflineAudioContext: ƒ nativeSetter()
get OffscreenCanvas: ƒ nativeGetter()
set OffscreenCanvas: ƒ nativeSetter()
get OffscreenCanvasRenderingContext2D: ƒ nativeGetter()
set OffscreenCanvasRenderingContext2D: ƒ nativeSetter()
get Option: ƒ nativeGetter()
set Option: ƒ nativeSetter()
get OrientationSensor: ƒ nativeGetter()
set OrientationSensor: ƒ nativeSetter()
get OscillatorNode: ƒ nativeGetter()
set OscillatorNode: ƒ nativeSetter()
get OverconstrainedError: ƒ nativeGetter()
set OverconstrainedError: ƒ nativeSetter()
get PageTransitionEvent: ƒ nativeGetter()
set PageTransitionEvent: ƒ nativeSetter()
get PannerNode: ƒ nativeGetter()
set PannerNode: ƒ nativeSetter()
get PasswordCredential: ƒ nativeGetter()
set PasswordCredential: ƒ nativeSetter()
get Path2D: ƒ nativeGetter()
set Path2D: ƒ nativeSetter()
get PaymentAddress: ƒ nativeGetter()
set PaymentAddress: ƒ nativeSetter()
get PaymentInstruments: ƒ nativeGetter()
set PaymentInstruments: ƒ nativeSetter()
get PaymentManager: ƒ nativeGetter()
set PaymentManager: ƒ nativeSetter()
get PaymentRequest: ƒ nativeGetter()
set PaymentRequest: ƒ nativeSetter()
get PaymentRequestUpdateEvent: ƒ nativeGetter()
set PaymentRequestUpdateEvent: ƒ nativeSetter()
get PaymentResponse: ƒ nativeGetter()
set PaymentResponse: ƒ nativeSetter()
get Performance: ƒ nativeGetter()
set Performance: ƒ nativeSetter()
get PerformanceEntry: ƒ nativeGetter()
set PerformanceEntry: ƒ nativeSetter()
get PerformanceLongTaskTiming: ƒ nativeGetter()
set PerformanceLongTaskTiming: ƒ nativeSetter()
get PerformanceMark: ƒ nativeGetter()
set PerformanceMark: ƒ nativeSetter()
get PerformanceMeasure: ƒ nativeGetter()
set PerformanceMeasure: ƒ nativeSetter()
get PerformanceNavigation: ƒ nativeGetter()
set PerformanceNavigation: ƒ nativeSetter()
get PerformanceNavigationTiming: ƒ nativeGetter()
set PerformanceNavigationTiming: ƒ nativeSetter()
get PerformanceObserver: ƒ nativeGetter()
set PerformanceObserver: ƒ nativeSetter()
get PerformanceObserverEntryList: ƒ nativeGetter()
set PerformanceObserverEntryList: ƒ nativeSetter()
get PerformancePaintTiming: ƒ nativeGetter()
set PerformancePaintTiming: ƒ nativeSetter()
get PerformanceResourceTiming: ƒ nativeGetter()
set PerformanceResourceTiming: ƒ nativeSetter()
get PerformanceServerTiming: ƒ nativeGetter()
set PerformanceServerTiming: ƒ nativeSetter()
get PerformanceTiming: ƒ nativeGetter()
set PerformanceTiming: ƒ nativeSetter()
get PeriodicWave: ƒ nativeGetter()
set PeriodicWave: ƒ nativeSetter()
get PermissionStatus: ƒ nativeGetter()
set PermissionStatus: ƒ nativeSetter()
get Permissions: ƒ nativeGetter()
set Permissions: ƒ nativeSetter()
get PhotoCapabilities: ƒ nativeGetter()
set PhotoCapabilities: ƒ nativeSetter()
get PictureInPictureWindow: ƒ nativeGetter()
set PictureInPictureWindow: ƒ nativeSetter()
get Plugin: ƒ nativeGetter()
set Plugin: ƒ nativeSetter()
get PluginArray: ƒ nativeGetter()
set PluginArray: ƒ nativeSetter()
get PointerEvent: ƒ nativeGetter()
set PointerEvent: ƒ nativeSetter()
get PopStateEvent: ƒ nativeGetter()
set PopStateEvent: ƒ nativeSetter()
get Presentation: ƒ nativeGetter()
set Presentation: ƒ nativeSetter()
get PresentationAvailability: ƒ nativeGetter()
set PresentationAvailability: ƒ nativeSetter()
get PresentationConnection: ƒ nativeGetter()
set PresentationConnection: ƒ nativeSetter()
get PresentationConnectionAvailableEvent: ƒ nativeGetter()
set PresentationConnectionAvailableEvent: ƒ nativeSetter()
get PresentationConnectionCloseEvent: ƒ nativeGetter()
set PresentationConnectionCloseEvent: ƒ nativeSetter()
get PresentationConnectionList: ƒ nativeGetter()
set PresentationConnectionList: ƒ nativeSetter()
get PresentationReceiver: ƒ nativeGetter()
set PresentationReceiver: ƒ nativeSetter()
get PresentationRequest: ƒ nativeGetter()
set PresentationRequest: ƒ nativeSetter()
get ProcessingInstruction: ƒ nativeGetter()
set ProcessingInstruction: ƒ nativeSetter()
get ProgressEvent: ƒ nativeGetter()
set ProgressEvent: ƒ nativeSetter()
get PromiseRejectionEvent: ƒ nativeGetter()
set PromiseRejectionEvent: ƒ nativeSetter()
get PublicKeyCredential: ƒ nativeGetter()
set PublicKeyCredential: ƒ nativeSetter()
get PushManager: ƒ nativeGetter()
set PushManager: ƒ nativeSetter()
get PushSubscription: ƒ nativeGetter()
set PushSubscription: ƒ nativeSetter()
get PushSubscriptionOptions: ƒ nativeGetter()
set PushSubscriptionOptions: ƒ nativeSetter()
get RTCCertificate: ƒ nativeGetter()
set RTCCertificate: ƒ nativeSetter()
get RTCDTMFSender: ƒ nativeGetter()
set RTCDTMFSender: ƒ nativeSetter()
get RTCDTMFToneChangeEvent: ƒ nativeGetter()
set RTCDTMFToneChangeEvent: ƒ nativeSetter()
get RTCDataChannel: ƒ nativeGetter()
set RTCDataChannel: ƒ nativeSetter()
get RTCDataChannelEvent: ƒ nativeGetter()
set RTCDataChannelEvent: ƒ nativeSetter()
get RTCIceCandidate: ƒ nativeGetter()
set RTCIceCandidate: ƒ nativeSetter()
get RTCPeerConnection: ƒ nativeGetter()
set RTCPeerConnection: ƒ nativeSetter()
get RTCPeerConnectionIceEvent: ƒ nativeGetter()
set RTCPeerConnectionIceEvent: ƒ nativeSetter()
get RTCRtpContributingSource: ƒ nativeGetter()
set RTCRtpContributingSource: ƒ nativeSetter()
get RTCRtpReceiver: ƒ nativeGetter()
set RTCRtpReceiver: ƒ nativeSetter()
get RTCRtpSender: ƒ nativeGetter()
set RTCRtpSender: ƒ nativeSetter()
get RTCRtpTransceiver: ƒ nativeGetter()
set RTCRtpTransceiver: ƒ nativeSetter()
get RTCSessionDescription: ƒ nativeGetter()
set RTCSessionDescription: ƒ nativeSetter()
get RTCStatsReport: ƒ nativeGetter()
set RTCStatsReport: ƒ nativeSetter()
get RTCTrackEvent: ƒ nativeGetter()
set RTCTrackEvent: ƒ nativeSetter()
get RadioNodeList: ƒ nativeGetter()
set RadioNodeList: ƒ nativeSetter()
get Range: ƒ nativeGetter()
set Range: ƒ nativeSetter()
get RelativeOrientationSensor: ƒ nativeGetter()
set RelativeOrientationSensor: ƒ nativeSetter()
get RemotePlayback: ƒ nativeGetter()
set RemotePlayback: ƒ nativeSetter()
get ReportingObserver: ƒ nativeGetter()
set ReportingObserver: ƒ nativeSetter()
get ResizeObserver: ƒ nativeGetter()
set ResizeObserver: ƒ nativeSetter()
get ResizeObserverEntry: ƒ nativeGetter()
set ResizeObserverEntry: ƒ nativeSetter()
get SVGAElement: ƒ nativeGetter()
set SVGAElement: ƒ nativeSetter()
get SVGAngle: ƒ nativeGetter()
set SVGAngle: ƒ nativeSetter()
get SVGAnimateElement: ƒ nativeGetter()
set SVGAnimateElement: ƒ nativeSetter()
get SVGAnimateMotionElement: ƒ nativeGetter()
set SVGAnimateMotionElement: ƒ nativeSetter()
get SVGAnimateTransformElement: ƒ nativeGetter()
set SVGAnimateTransformElement: ƒ nativeSetter()
get SVGAnimatedAngle: ƒ nativeGetter()
set SVGAnimatedAngle: ƒ nativeSetter()
get SVGAnimatedBoolean: ƒ nativeGetter()
set SVGAnimatedBoolean: ƒ nativeSetter()
get SVGAnimatedEnumeration: ƒ nativeGetter()
set SVGAnimatedEnumeration: ƒ nativeSetter()
get SVGAnimatedInteger: ƒ nativeGetter()
set SVGAnimatedInteger: ƒ nativeSetter()
get SVGAnimatedLength: ƒ nativeGetter()
set SVGAnimatedLength: ƒ nativeSetter()
get SVGAnimatedLengthList: ƒ nativeGetter()
set SVGAnimatedLengthList: ƒ nativeSetter()
get SVGAnimatedNumber: ƒ nativeGetter()
set SVGAnimatedNumber: ƒ nativeSetter()
get SVGAnimatedNumberList: ƒ nativeGetter()
set SVGAnimatedNumberList: ƒ nativeSetter()
get SVGAnimatedPreserveAspectRatio: ƒ nativeGetter()
set SVGAnimatedPreserveAspectRatio: ƒ nativeSetter()
get SVGAnimatedRect: ƒ nativeGetter()
set SVGAnimatedRect: ƒ nativeSetter()
get SVGAnimatedString: ƒ nativeGetter()
set SVGAnimatedString: ƒ nativeSetter()
get SVGAnimatedTransformList: ƒ nativeGetter()
set SVGAnimatedTransformList: ƒ nativeSetter()
get SVGAnimationElement: ƒ nativeGetter()
set SVGAnimationElement: ƒ nativeSetter()
get SVGCircleElement: ƒ nativeGetter()
set SVGCircleElement: ƒ nativeSetter()
get SVGClipPathElement: ƒ nativeGetter()
set SVGClipPathElement: ƒ nativeSetter()
get SVGComponentTransferFunctionElement: ƒ nativeGetter()
set SVGComponentTransferFunctionElement: ƒ nativeSetter()
get SVGDefsElement: ƒ nativeGetter()
set SVGDefsElement: ƒ nativeSetter()
get SVGDescElement: ƒ nativeGetter()
set SVGDescElement: ƒ nativeSetter()
get SVGDiscardElement: ƒ nativeGetter()
set SVGDiscardElement: ƒ nativeSetter()
get SVGElement: ƒ nativeGetter()
set SVGElement: ƒ nativeSetter()
get SVGEllipseElement: ƒ nativeGetter()
set SVGEllipseElement: ƒ nativeSetter()
get SVGFEBlendElement: ƒ nativeGetter()
set SVGFEBlendElement: ƒ nativeSetter()
get SVGFEColorMatrixElement: ƒ nativeGetter()
set SVGFEColorMatrixElement: ƒ nativeSetter()
get SVGFEComponentTransferElement: ƒ nativeGetter()
set SVGFEComponentTransferElement: ƒ nativeSetter()
get SVGFECompositeElement: ƒ nativeGetter()
set SVGFECompositeElement: ƒ nativeSetter()
get SVGFEConvolveMatrixElement: ƒ nativeGetter()
set SVGFEConvolveMatrixElement: ƒ nativeSetter()
get SVGFEDiffuseLightingElement: ƒ nativeGetter()
set SVGFEDiffuseLightingElement: ƒ nativeSetter()
get SVGFEDisplacementMapElement: ƒ nativeGetter()
set SVGFEDisplacementMapElement: ƒ nativeSetter()
get SVGFEDistantLightElement: ƒ nativeGetter()
set SVGFEDistantLightElement: ƒ nativeSetter()
get SVGFEDropShadowElement: ƒ nativeGetter()
set SVGFEDropShadowElement: ƒ nativeSetter()
get SVGFEFloodElement: ƒ nativeGetter()
set SVGFEFloodElement: ƒ nativeSetter()
get SVGFEFuncAElement: ƒ nativeGetter()
set SVGFEFuncAElement: ƒ nativeSetter()
get SVGFEFuncBElement: ƒ nativeGetter()
set SVGFEFuncBElement: ƒ nativeSetter()
get SVGFEFuncGElement: ƒ nativeGetter()
set SVGFEFuncGElement: ƒ nativeSetter()
get SVGFEFuncRElement: ƒ nativeGetter()
set SVGFEFuncRElement: ƒ nativeSetter()
get SVGFEGaussianBlurElement: ƒ nativeGetter()
set SVGFEGaussianBlurElement: ƒ nativeSetter()
get SVGFEImageElement: ƒ nativeGetter()
set SVGFEImageElement: ƒ nativeSetter()
get SVGFEMergeElement: ƒ nativeGetter()
set SVGFEMergeElement: ƒ nativeSetter()
get SVGFEMergeNodeElement: ƒ nativeGetter()
set SVGFEMergeNodeElement: ƒ nativeSetter()
get SVGFEMorphologyElement: ƒ nativeGetter()
set SVGFEMorphologyElement: ƒ nativeSetter()
get SVGFEOffsetElement: ƒ nativeGetter()
set SVGFEOffsetElement: ƒ nativeSetter()
get SVGFEPointLightElement: ƒ nativeGetter()
set SVGFEPointLightElement: ƒ nativeSetter()
get SVGFESpecularLightingElement: ƒ nativeGetter()
set SVGFESpecularLightingElement: ƒ nativeSetter()
get SVGFESpotLightElement: ƒ nativeGetter()
set SVGFESpotLightElement: ƒ nativeSetter()
get SVGFETileElement: ƒ nativeGetter()
set SVGFETileElement: ƒ nativeSetter()
get SVGFETurbulenceElement: ƒ nativeGetter()
set SVGFETurbulenceElement: ƒ nativeSetter()
get SVGFilterElement: ƒ nativeGetter()
set SVGFilterElement: ƒ nativeSetter()
get SVGForeignObjectElement: ƒ nativeGetter()
set SVGForeignObjectElement: ƒ nativeSetter()
get SVGGElement: ƒ nativeGetter()
set SVGGElement: ƒ nativeSetter()
get SVGGeometryElement: ƒ nativeGetter()
set SVGGeometryElement: ƒ nativeSetter()
get SVGGradientElement: ƒ nativeGetter()
set SVGGradientElement: ƒ nativeSetter()
get SVGGraphicsElement: ƒ nativeGetter()
set SVGGraphicsElement: ƒ nativeSetter()
get SVGImageElement: ƒ nativeGetter()
set SVGImageElement: ƒ nativeSetter()
get SVGLength: ƒ nativeGetter()
set SVGLength: ƒ nativeSetter()
get SVGLengthList: ƒ nativeGetter()
set SVGLengthList: ƒ nativeSetter()
get SVGLineElement: ƒ nativeGetter()
set SVGLineElement: ƒ nativeSetter()
get SVGLinearGradientElement: ƒ nativeGetter()
set SVGLinearGradientElement: ƒ nativeSetter()
get SVGMPathElement: ƒ nativeGetter()
set SVGMPathElement: ƒ nativeSetter()
get SVGMarkerElement: ƒ nativeGetter()
set SVGMarkerElement: ƒ nativeSetter()
get SVGMaskElement: ƒ nativeGetter()
set SVGMaskElement: ƒ nativeSetter()
get SVGMatrix: ƒ nativeGetter()
set SVGMatrix: ƒ nativeSetter()
get SVGMetadataElement: ƒ nativeGetter()
set SVGMetadataElement: ƒ nativeSetter()
get SVGNumber: ƒ nativeGetter()
set SVGNumber: ƒ nativeSetter()
get SVGNumberList: ƒ nativeGetter()
set SVGNumberList: ƒ nativeSetter()
get SVGPathElement: ƒ nativeGetter()
set SVGPathElement: ƒ nativeSetter()
get SVGPatternElement: ƒ nativeGetter()
set SVGPatternElement: ƒ nativeSetter()
get SVGPoint: ƒ nativeGetter()
set SVGPoint: ƒ nativeSetter()
get SVGPointList: ƒ nativeGetter()
set SVGPointList: ƒ nativeSetter()
get SVGPolygonElement: ƒ nativeGetter()
set SVGPolygonElement: ƒ nativeSetter()
get SVGPolylineElement: ƒ nativeGetter()
set SVGPolylineElement: ƒ nativeSetter()
get SVGPreserveAspectRatio: ƒ nativeGetter()
set SVGPreserveAspectRatio: ƒ nativeSetter()
get SVGRadialGradientElement: ƒ nativeGetter()
set SVGRadialGradientElement: ƒ nativeSetter()
get SVGRect: ƒ nativeGetter()
set SVGRect: ƒ nativeSetter()
get SVGRectElement: ƒ nativeGetter()
set SVGRectElement: ƒ nativeSetter()
get SVGSVGElement: ƒ nativeGetter()
set SVGSVGElement: ƒ nativeSetter()
get SVGScriptElement: ƒ nativeGetter()
set SVGScriptElement: ƒ nativeSetter()
get SVGSetElement: ƒ nativeGetter()
set SVGSetElement: ƒ nativeSetter()
get SVGStopElement: ƒ nativeGetter()
set SVGStopElement: ƒ nativeSetter()
get SVGStringList: ƒ nativeGetter()
set SVGStringList: ƒ nativeSetter()
get SVGStyleElement: ƒ nativeGetter()
set SVGStyleElement: ƒ nativeSetter()
get SVGSwitchElement: ƒ nativeGetter()
set SVGSwitchElement: ƒ nativeSetter()
get SVGSymbolElement: ƒ nativeGetter()
set SVGSymbolElement: ƒ nativeSetter()
get SVGTSpanElement: ƒ nativeGetter()
set SVGTSpanElement: ƒ nativeSetter()
get SVGTextContentElement: ƒ nativeGetter()
set SVGTextContentElement: ƒ nativeSetter()
get SVGTextElement: ƒ nativeGetter()
set SVGTextElement: ƒ nativeSetter()
get SVGTextPathElement: ƒ nativeGetter()
set SVGTextPathElement: ƒ nativeSetter()
get SVGTextPositioningElement: ƒ nativeGetter()
set SVGTextPositioningElement: ƒ nativeSetter()
get SVGTitleElement: ƒ nativeGetter()
set SVGTitleElement: ƒ nativeSetter()
get SVGTransform: ƒ nativeGetter()
set SVGTransform: ƒ nativeSetter()
get SVGTransformList: ƒ nativeGetter()
set SVGTransformList: ƒ nativeSetter()
get SVGUnitTypes: ƒ nativeGetter()
set SVGUnitTypes: ƒ nativeSetter()
get SVGUseElement: ƒ nativeGetter()
set SVGUseElement: ƒ nativeSetter()
get SVGViewElement: ƒ nativeGetter()
set SVGViewElement: ƒ nativeSetter()
get Screen: ƒ nativeGetter()
set Screen: ƒ nativeSetter()
get ScreenOrientation: ƒ nativeGetter()
set ScreenOrientation: ƒ nativeSetter()
get ScriptProcessorNode: ƒ nativeGetter()
set ScriptProcessorNode: ƒ nativeSetter()
get SecurityPolicyViolationEvent: ƒ nativeGetter()
set SecurityPolicyViolationEvent: ƒ nativeSetter()
get Selection: ƒ nativeGetter()
set Selection: ƒ nativeSetter()
get Sensor: ƒ nativeGetter()
set Sensor: ƒ nativeSetter()
get SensorErrorEvent: ƒ nativeGetter()
set SensorErrorEvent: ƒ nativeSetter()
get ServiceWorker: ƒ nativeGetter()
set ServiceWorker: ƒ nativeSetter()
get ServiceWorkerContainer: ƒ nativeGetter()
set ServiceWorkerContainer: ƒ nativeSetter()
get ServiceWorkerRegistration: ƒ nativeGetter()
set ServiceWorkerRegistration: ƒ nativeSetter()
get ShadowRoot: ƒ nativeGetter()
set ShadowRoot: ƒ nativeSetter()
get SharedWorker: ƒ nativeGetter()
set SharedWorker: ƒ nativeSetter()
get SourceBuffer: ƒ nativeGetter()
set SourceBuffer: ƒ nativeSetter()
get SourceBufferList: ƒ nativeGetter()
set SourceBufferList: ƒ nativeSetter()
get SpeechSynthesisEvent: ƒ nativeGetter()
set SpeechSynthesisEvent: ƒ nativeSetter()
get SpeechSynthesisUtterance: ƒ nativeGetter()
set SpeechSynthesisUtterance: ƒ nativeSetter()
get StaticRange: ƒ nativeGetter()
set StaticRange: ƒ nativeSetter()
get StereoPannerNode: ƒ nativeGetter()
set StereoPannerNode: ƒ nativeSetter()
get Storage: ƒ nativeGetter()
set Storage: ƒ nativeSetter()
get StorageEvent: ƒ nativeGetter()
set StorageEvent: ƒ nativeSetter()
get StorageManager: ƒ nativeGetter()
set StorageManager: ƒ nativeSetter()
get StylePropertyMap: ƒ nativeGetter()
set StylePropertyMap: ƒ nativeSetter()
get StylePropertyMapReadOnly: ƒ nativeGetter()
set StylePropertyMapReadOnly: ƒ nativeSetter()
get StyleSheet: ƒ nativeGetter()
set StyleSheet: ƒ nativeSetter()
get StyleSheetList: ƒ nativeGetter()
set StyleSheetList: ƒ nativeSetter()
get SubtleCrypto: ƒ nativeGetter()
set SubtleCrypto: ƒ nativeSetter()
get SyncManager: ƒ nativeGetter()
set SyncManager: ƒ nativeSetter()
get TaskAttributionTiming: ƒ nativeGetter()
set TaskAttributionTiming: ƒ nativeSetter()
get Text: ƒ nativeGetter()
set Text: ƒ nativeSetter()
get TextDecoder: ƒ nativeGetter()
set TextDecoder: ƒ nativeSetter()
get TextEncoder: ƒ nativeGetter()
set TextEncoder: ƒ nativeSetter()
get TextEvent: ƒ nativeGetter()
set TextEvent: ƒ nativeSetter()
get TextMetrics: ƒ nativeGetter()
set TextMetrics: ƒ nativeSetter()
get TextTrack: ƒ nativeGetter()
set TextTrack: ƒ nativeSetter()
get TextTrackCue: ƒ nativeGetter()
set TextTrackCue: ƒ nativeSetter()
get TextTrackCueList: ƒ nativeGetter()
set TextTrackCueList: ƒ nativeSetter()
get TextTrackList: ƒ nativeGetter()
set TextTrackList: ƒ nativeSetter()
get TimeRanges: ƒ nativeGetter()
set TimeRanges: ƒ nativeSetter()
get Touch: ƒ nativeGetter()
set Touch: ƒ nativeSetter()
get TouchEvent: ƒ nativeGetter()
set TouchEvent: ƒ nativeSetter()
get TouchList: ƒ nativeGetter()
set TouchList: ƒ nativeSetter()
get TrackEvent: ƒ nativeGetter()
set TrackEvent: ƒ nativeSetter()
get TransitionEvent: ƒ nativeGetter()
set TransitionEvent: ƒ nativeSetter()
get TreeWalker: ƒ nativeGetter()
set TreeWalker: ƒ nativeSetter()
get UIEvent: ƒ nativeGetter()
set UIEvent: ƒ nativeSetter()
get URL: ƒ nativeGetter()
set URL: ƒ nativeSetter()
get URLSearchParams: ƒ nativeGetter()
set URLSearchParams: ƒ nativeSetter()
get USB: ƒ nativeGetter()
set USB: ƒ nativeSetter()
get USBAlternateInterface: ƒ nativeGetter()
set USBAlternateInterface: ƒ nativeSetter()
get USBConfiguration: ƒ nativeGetter()
set USBConfiguration: ƒ nativeSetter()
get USBConnectionEvent: ƒ nativeGetter()
set USBConnectionEvent: ƒ nativeSetter()
get USBDevice: ƒ nativeGetter()
set USBDevice: ƒ nativeSetter()
get USBEndpoint: ƒ nativeGetter()
set USBEndpoint: ƒ nativeSetter()
get USBInTransferResult: ƒ nativeGetter()
set USBInTransferResult: ƒ nativeSetter()
get USBInterface: ƒ nativeGetter()
set USBInterface: ƒ nativeSetter()
get USBIsochronousInTransferPacket: ƒ nativeGetter()
set USBIsochronousInTransferPacket: ƒ nativeSetter()
get USBIsochronousInTransferResult: ƒ nativeGetter()
set USBIsochronousInTransferResult: ƒ nativeSetter()
get USBIsochronousOutTransferPacket: ƒ nativeGetter()
set USBIsochronousOutTransferPacket: ƒ nativeSetter()
get USBIsochronousOutTransferResult: ƒ nativeGetter()
set USBIsochronousOutTransferResult: ƒ nativeSetter()
get USBOutTransferResult: ƒ nativeGetter()
set USBOutTransferResult: ƒ nativeSetter()
get VTTCue: ƒ nativeGetter()
set VTTCue: ƒ nativeSetter()
get ValidityState: ƒ nativeGetter()
set ValidityState: ƒ nativeSetter()
get VisualViewport: ƒ nativeGetter()
set VisualViewport: ƒ nativeSetter()
get WaveShaperNode: ƒ nativeGetter()
set WaveShaperNode: ƒ nativeSetter()
get WebGL2RenderingContext: ƒ nativeGetter()
set WebGL2RenderingContext: ƒ nativeSetter()
get WebGLActiveInfo: ƒ nativeGetter()
set WebGLActiveInfo: ƒ nativeSetter()
get WebGLBuffer: ƒ nativeGetter()
set WebGLBuffer: ƒ nativeSetter()
get WebGLContextEvent: ƒ nativeGetter()
set WebGLContextEvent: ƒ nativeSetter()
get WebGLFramebuffer: ƒ nativeGetter()
set WebGLFramebuffer: ƒ nativeSetter()
get WebGLProgram: ƒ nativeGetter()
set WebGLProgram: ƒ nativeSetter()
get WebGLQuery: ƒ nativeGetter()
set WebGLQuery: ƒ nativeSetter()
get WebGLRenderbuffer: ƒ nativeGetter()
set WebGLRenderbuffer: ƒ nativeSetter()
get WebGLRenderingContext: ƒ nativeGetter()
set WebGLRenderingContext: ƒ nativeSetter()
get WebGLSampler: ƒ nativeGetter()
set WebGLSampler: ƒ nativeSetter()
get WebGLShader: ƒ nativeGetter()
set WebGLShader: ƒ nativeSetter()
get WebGLShaderPrecisionFormat: ƒ nativeGetter()
set WebGLShaderPrecisionFormat: ƒ nativeSetter()
get WebGLSync: ƒ nativeGetter()
set WebGLSync: ƒ nativeSetter()
get WebGLTexture: ƒ nativeGetter()
set WebGLTexture: ƒ nativeSetter()
get WebGLTransformFeedback: ƒ nativeGetter()
set WebGLTransformFeedback: ƒ nativeSetter()
get WebGLUniformLocation: ƒ nativeGetter()
set WebGLUniformLocation: ƒ nativeSetter()
get WebGLVertexArrayObject: ƒ nativeGetter()
set WebGLVertexArrayObject: ƒ nativeSetter()
get WebKitAnimationEvent: ƒ nativeGetter()
set WebKitAnimationEvent: ƒ nativeSetter()
get WebKitCSSMatrix: ƒ nativeGetter()
set WebKitCSSMatrix: ƒ nativeSetter()
get WebKitMutationObserver: ƒ nativeGetter()
set WebKitMutationObserver: ƒ nativeSetter()
get WebKitTransitionEvent: ƒ nativeGetter()
set WebKitTransitionEvent: ƒ nativeSetter()
get WebSocket: ƒ nativeGetter()
set WebSocket: ƒ nativeSetter()
get WheelEvent: ƒ nativeGetter()
set WheelEvent: ƒ nativeSetter()
get Window: ƒ nativeGetter()
set Window: ƒ nativeSetter()
get Worker: ƒ nativeGetter()
set Worker: ƒ nativeSetter()
get Worklet: ƒ nativeGetter()
set Worklet: ƒ nativeSetter()
get XMLDocument: ƒ nativeGetter()
set XMLDocument: ƒ nativeSetter()
get XMLHttpRequest: ƒ nativeGetter()
set XMLHttpRequest: ƒ nativeSetter()
get XMLHttpRequestEventTarget: ƒ nativeGetter()
set XMLHttpRequestEventTarget: ƒ nativeSetter()
get XMLHttpRequestUpload: ƒ nativeGetter()
set XMLHttpRequestUpload: ƒ nativeSetter()
get XMLSerializer: ƒ nativeGetter()
set XMLSerializer: ƒ nativeSetter()
get XPathEvaluator: ƒ nativeGetter()
set XPathEvaluator: ƒ nativeSetter()
get XPathExpression: ƒ nativeGetter()
set XPathExpression: ƒ nativeSetter()
get XPathResult: ƒ nativeGetter()
set XPathResult: ƒ nativeSetter()
get XSLTProcessor: ƒ nativeGetter()
set XSLTProcessor: ƒ nativeSetter()
get blur: ƒ nativeGetter()
set blur: ƒ nativeSetter()
get close: ƒ nativeGetter()
set close: ƒ nativeSetter()
get closed: ƒ nativeGetter()
set closed: ƒ nativeSetter()
get focus: ƒ nativeGetter()
set focus: ƒ nativeSetter()
get frames: ƒ nativeGetter()
set frames: ƒ nativeSetter()
get length: ƒ nativeGetter()
set length: ƒ nativeSetter()
get location: ƒ nativeGetter()
set location: ƒ nativeSetter()
get opener: ƒ nativeGetter()
set opener: ƒ nativeSetter()
get parent: ƒ nativeGetter()
set parent: ƒ nativeSetter()
get postMessage: ƒ nativeGetter()
set postMessage: ƒ nativeSetter()
get self: ƒ nativeGetter()
set self: ƒ nativeSetter()
get top: ƒ nativeGetter()
set top: ƒ nativeSetter()
get webkitMediaStream: ƒ nativeGetter()
set webkitMediaStream: ƒ nativeSetter()
get webkitRTCPeerConnection: ƒ nativeGetter()
set webkitRTCPeerConnection: ƒ nativeSetter()
get webkitSpeechGrammar: ƒ nativeGetter()
set webkitSpeechGrammar: ƒ nativeSetter()
get webkitSpeechGrammarList: ƒ nativeGetter()
set webkitSpeechGrammarList: ƒ nativeSetter()
get webkitSpeechRecognition: ƒ nativeGetter()
set webkitSpeechRecognition: ƒ nativeSetter()
get webkitSpeechRecognitionError: ƒ nativeGetter()
set webkitSpeechRecognitionError: ƒ nativeSetter()
get webkitSpeechRecognitionEvent: ƒ nativeGetter()
set webkitSpeechRecognitionEvent: ƒ nativeSetter()
get webkitURL: ƒ nativeGetter()
set webkitURL: ƒ nativeSetter()
__proto__: Window */
